.Dd October 13, 2019
.Dt JSON2TSV 1
.Os
.Sh NAME
.Nm json2tsv
.Nd convert JSON to TSV
.Sh SYNOPSIS
.Nm
.Op Fl n
.Sh DESCRIPTION
.Nm
reads JSON data from stdin.
It outputs each JSON type to a TAB-Separated Value format per line.
The
.Fl n
flag can be used to show the indices for array types (by default off).
.Sh TAB-SEPARATED VALUE FORMAT
The output format per line is:
.Bd -literal
nodename<TAB>type<TAB>value<LF>
.Ed
.Pp
The nodename and value are escaped (\\n, \\t and \\\\).
Control-characters are removed.
.Pp
The type can be: o (for object), a (for array), p (for primitive such as
true, false, null, a number) or s (for string).
.Sh SEE ALSO
.Xr awk 1 ,
.Xr grep 1
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
.Sh CAVEATS
.Bl -item
.It
Characters in object keys such as a dot or brackets are not changed, this
can change the meaning of the nodename field.
.It
The JSON parser handles all valid JSON.
It also handles some invalid JSON like object key strings without quoting (").
.It
The maximum depth of objects or arrays is hard-coded to 64 levels deep.
.El
